FROM python:3.11-slim
WORKDIR /app
RUN pip install pytest requests pyjwt redis pillow
# Copy the tests folder from the root into the container
COPY tests/ ./tests/
# Run pytest
CMD ["pytest", "-v", "-s", "tests/test_api.py"]
